import { FEEDBACK_ACTIONS } from './store/feedback.ts';
import { DEFAULT_LIMITS } from './contract/limits.ts';

/**
 * The one source of truth for what each command accepts. `review-voice
 * <command> --help` prints one entry; the top-level help prints the list of
 * summaries followed by every entry.
 *
 * `body` starts with the synopsis line, then the sections that apply: Flags,
 * Positional, Reads (stdin), Writes, Exit codes.
 */
export interface CommandHelp {
  summary: string;
  body: string;
}

const lines = (...rows: string[]): string => rows.join('\n');

export const COMMAND_HELP: Record<string, CommandHelp> = {
  diff: {
    summary: 'Acquire the diff under review as structured JSON',
    body: lines(
      'review-voice diff [flags]',
      '  Acquire the diff under review as structured JSON.',
      '',
      'Flags:',
      '  --base <ref>           Review against a base ref (e.g. origin/main)',
      '  --staged               Review staged changes only',
      '  --pr <number>          Review a GitHub pull request (needs --repository)',
      '  --full                 On --pr, review the complete pull request again',
      '  --since <sha>          On --pr, the head last reviewed (overrides the record)',
      '  --repository <name>    owner/repo for --pr (default: the git remote)',
      '  --include-generated    Include lock files, generated, vendored and binary files',
      '  --out <dir>            Write diff.patch and files.json, print a summary',
      'Reads: nothing on stdin (--pr reads the pull request from GitHub, read-only).',
      'Writes: the diff as JSON on stdout, or with --out, diff.patch and files.json in <dir>.',
      'Exit codes: 0 ok, 2 bad invocation or unreadable input.',
    ),
  },
  symbols: {
    summary: 'Collect changed symbols and their lexical reference paths',
    body: lines(
      'review-voice symbols --diff-file <path> [flags]',
      '  Collect changed symbols and their lexical reference paths.',
      '',
      'Flags:',
      '  --diff-file <path>     Unified diff whose changed symbols to inspect (required)',
      '  --base <ref>           Search this committed tree, not the working tree',
      '                         (on --pr: refs.mergeBase)',
      '  --max-ms <n>           Time budget; unfinished files are inconclusive (default 60000)',
      '  --out <path>           Write <path> or <dir>/symbols.json instead of stdout',
      'Reads: nothing on stdin.',
      'Writes: JSON on stdout, or to --out.',
      'Exit codes: 0 ok, 2 bad invocation or unreadable input.',
    ),
  },
  anchors: {
    summary: 'Resolve one inline anchor per finding of the review on stdin',
    body: lines(
      'review-voice anchors [flags]',
      '  One inline anchor per finding of the review on stdin, read from its text.',
      '',
      'Flags:',
      '  --diff-file <path>     Unified diff; a line outside its hunks is unanchorable',
      '  --scores <path>        Scores; a stale-consumer finding is unanchorable',
      'Reads: the validated review on stdin.',
      'Writes: JSON on stdout.',
      'Exit codes: 0 ok, 2 bad invocation or unreadable input.',
    ),
  },
  thread: {
    summary: "Read a pull request's existing comments, with resolution",
    body: lines(
      'review-voice thread --pr <number> [flags]',
      "  Read a pull request's existing comments (read-only).",
      '',
      'Flags:',
      '  --pr <number>          Pull request whose existing comments to read (required)',
      '  --repository <name>    owner/repo; inferred from the git remote if absent',
      '  --out <path>           Write <path> or <dir>/thread.json instead of stdout',
      'Reads: nothing on stdin (reads GitHub, read-only).',
      'Writes: JSON on stdout, or to --out.',
      'Exit codes: 0 ok, 2 bad invocation, missing credential or repository not allowlisted.',
    ),
  },
  'follow-ups': {
    summary: 'Partly-addressed follow-ups of a pull request still open',
    body: lines(
      'review-voice follow-ups --pr <number> [flags]',
      '  List the partly-addressed follow-ups an earlier run of the pull request left open.',
      '',
      'Flags:',
      '  --pr <number>          Pull request whose open follow-ups to list (required; local store)',
      '  --repository <name>    owner/repo; inferred from the git remote if absent',
      'Reads: nothing on stdin; the local store.',
      'Writes: JSON on stdout. Nothing is stored.',
      'Exit codes: 0 ok, 2 bad invocation.',
    ),
  },
  'check-candidates': {
    summary: 'Validate analyst output against the candidate schema',
    body: lines(
      'review-voice check-candidates [flags]',
      '  Validate analyst output against the candidate schema.',
      '',
      'Flags:',
      '  --diff-file <path>     Require anchors on changed lines',
      '  --thread <path>        Drop thread repeats; flag near ones for the verifier',
      '  --owner <login>        Owner for --thread; default from config',
      '  --held-from <run-id>   Drop repeats of that run\'s held findings (needs --head)',
      '  --head <sha>           Head the candidates were produced against (with --held-from)',
      'Reads: candidates JSON on stdin.',
      'Writes: JSON on stdout.',
      'Exit codes: 0 valid, 2 invalid candidates or bad invocation.',
    ),
  },
  'check-verification': {
    summary: 'Validate verifier output from stdin, as score would',
    body: lines(
      'review-voice check-verification',
      '  Validate verifier output the way score would read it. Takes no flags.',
      '',
      'Reads: the evidence-verifier output on stdin.',
      'Writes: JSON on stdout.',
      'Exit codes: 0 valid, 2 malformed or bad invocation.',
    ),
  },
  context: {
    summary: 'Resolve config and the active policy stack as JSON',
    body: lines(
      'review-voice context',
      '  Resolve config and the active policy stack as JSON. Takes no flags.',
      '',
      'Reads: nothing on stdin.',
      'Writes: JSON on stdout.',
      'Exit codes: 0 ok, 2 not in a repository or unreadable config.',
    ),
  },
  conventions: {
    summary: "Collect the repository's own convention documents",
    body: lines(
      'review-voice conventions [flags]',
      "  Collect the repository's own convention documents.",
      '',
      'Flags:',
      '  --files <path>         files.json from diff --out, scoping nested docs',
      '  --path <p>             A changed path, repeatable, instead of --files',
      'Reads: nothing on stdin.',
      'Writes: JSON on stdout.',
      'Exit codes: 0 ok, 2 bad invocation.',
    ),
  },
  evidence: {
    summary: 'Run the configured static checks and emit structured signals',
    body: lines(
      'review-voice evidence',
      '  Run the configured static checks and emit structured signals. Takes no flags.',
      '',
      'Reads: nothing on stdin.',
      'Writes: JSON on stdout. Runs the commands configured under static evidence.',
      'Exit codes: 0 ok (a failing check is evidence, not an error), 2 not in a repository.',
    ),
  },
  verify: {
    summary: 'Second-pass verification by a configured command',
    body: lines(
      'review-voice verify [flags]',
      '  Second-pass verification of candidates by a configured command.',
      '',
      'Flags:',
      '  --diff-file <path>     The diff under review, not the working tree',
      '  --base <ref>           Base commit, only when it is readable locally',
      '  --head <ref>           Head commit, only when it is readable locally',
      '  --repository <name>    owner/repo, inferred from the git remote if absent',
      'Reads: candidates JSON on stdin.',
      'Writes: JSON report on stdout. Runs the configured verification command.',
      'Exit codes: 0 ok (a rejected finding is a result), 2 bad input or invocation.',
    ),
  },
  reconcile: {
    summary: 'Apply --second-pass verdicts; --tie-breaks settles disputes',
    body: lines(
      'review-voice reconcile --verification <path> --second-pass <path> [flags]',
      '  Apply the second pass to the candidates; a tie-break settles a dispute.',
      '',
      'Flags:',
      '  --verification <path>  The verifier output (required)',
      '  --second-pass <path>   The verify report (required)',
      '  --tie-breaks <path>    Rulings that settle disputes between the two',
      'Reads: the candidates JSON, before the second pass, on stdin.',
      'Writes: JSON on stdout; notes on stderr.',
      'Exit codes: 0 ok, 2 bad input or invocation.',
    ),
  },
  redact: {
    summary: 'Redact secrets from stdin (used before anything is stored)',
    body: lines(
      'review-voice redact [flags]',
      '  Redact secrets from stdin.',
      '',
      'Flags:',
      '  --json                 Emit the result as JSON',
      'Reads: the text to redact on stdin.',
      'Writes: the redacted text (or JSON) on stdout.',
      'Exit codes: 0 ok, 2 bad invocation.',
    ),
  },
  sync: {
    summary: 'Ingest review history from allowlisted repositories',
    body: lines(
      'review-voice sync [flags]',
      '  Ingest review history from allowlisted repositories.',
      '',
      'Flags:',
      '  --target <n>              Non-owner events to import (default 60 per',
      '                            repository, 250 to 1500); owner events all',
      '  --max-pulls <n>           Pull requests inspected per repository (default 60)',
      '  --include-conversation    Also read pull-request conversation comments',
      '  --dry-run                 Report the import without storing it',
      'Reads: nothing on stdin (reads GitHub, read-only).',
      'Writes: events and watermarks to the local store (not with --dry-run); JSON summary on stdout.',
      'Exit codes: 0 ok, 2 no allowlist, no owner reviewer, or credential problem.',
    ),
  },
  discover: {
    summary: 'List repositories the credential can see (reads no history)',
    body: lines(
      'review-voice discover',
      '  List repositories the credential can see. Reads no history. Takes no flags.',
      '',
      'Reads: nothing on stdin (reads GitHub, read-only).',
      'Writes: JSON on stdout.',
      'Exit codes: 0 ok, 2 credential problem.',
    ),
  },
  'consent-plan': {
    summary: 'Show exactly what a sync would read, before it reads it',
    body: lines(
      'review-voice consent-plan [flags]',
      '  Show exactly what a sync would read, before it reads it.',
      '',
      'Flags:',
      '  --owner <login>        Owner reviewer; default from config (required if unset)',
      '  --repo <owner/repo>    Repository to plan for, repeatable; default the allowlist',
      '  --target <n>           Non-owner events to plan for (default 250)',
      'Reads: nothing on stdin.',
      'Writes: JSON on stdout. Reads no history.',
      'Exit codes: 0 ok, 2 no owner or no repositories.',
    ),
  },
  purge: {
    summary: 'Delete stored data by repository, age, or entirely',
    body: lines(
      'review-voice purge (--repo <owner/repo> | --before <date> | --all) [--confirm]',
      '  Delete stored data by repository, age, or entirely.',
      '',
      'Flags (one scope required):',
      '  --repo <owner/repo>   Remove one repository\'s events',
      '  --before <ISO date>   Remove events older than a date',
      '  --all                 Remove everything, including runs and feedback',
      '  --confirm             Delete; without it, only a preview',
      'Reads: nothing on stdin.',
      'Writes: JSON preview on stdout; with --confirm, deletes from the local store.',
      'Exit codes: 0 ok, 2 no scope given.',
    ),
  },
  retrieve: {
    summary: 'Find weighted precedents for a candidate finding',
    body: lines(
      'review-voice retrieve --text <query> [flags]',
      '  Find weighted precedents for a candidate finding.',
      '',
      'Flags:',
      '  --text <query>        Candidate claim and failure mode (required)',
      '  --repository <name>   Prefer precedents from this repository',
      '  --path <path>         Prefer precedents on this file',
      '  --language <lang>     Prefer precedents in this language',
      '  --max-positive <n>    Positive precedents to return (default 3)',
      '  --max-negative <n>    Negative precedents to return (default 2)',
      'Reads: nothing on stdin; the local store.',
      'Writes: JSON on stdout.',
      'Exit codes: 0 ok, 2 bad invocation.',
    ),
  },
  score: {
    summary: 'Score candidates from stdin against retrieved precedents',
    body: lines(
      'review-voice score [flags]',
      '  Score candidates against retrieved precedents.',
      '',
      'Flags:',
      '  --base <ref>              Reviewed tree for absence checks',
      '  --verification <path>     Verifier output for confidence and fix rendering',
      '  --exclude-pull <n>        Exclude precedents from this pull request',
      '  --min-confidence <n>      Verifier confidence gate (default 0.8)',
      '  --min-analyst-confidence <n>  Analyst-only gate (default 0.7)',
      '  --thread <path>           Existing pull-request comments',
      '  --diff-file <path>        Diff for reach and anchor checks',
      '  --min-score <n>           Final score gate (default 0.68)',
      '  --repository <name>       Prefer precedents from this repository',
      '  --owner <login>           Owner whose precedents count; default from config',
      'Reads: candidates JSON on stdin.',
      'Writes: JSON scores on stdout. Every entry names its candidate as candidate_id,',
      '  like candidates and verification; candidateId is still written beside it',
      '  but is deprecated.',
      'Exit codes: 0 ok, 2 malformed candidates or bad invocation.',
    ),
  },
  calibrate: {
    summary: 'Show proposed policy changes and their evidence',
    body: lines(
      'review-voice calibrate',
      '  Show proposed policy changes and their evidence. Takes no flags.',
      '',
      'Reads: nothing on stdin; the local store.',
      'Writes: JSON on stdout; stores the proposal as a pending policy version.',
      'Exit codes: 0 ok.',
    ),
  },
  policy: {
    summary: 'show | approve <id> | rollback <version>',
    body: lines(
      'review-voice policy [show | approve <id> | rollback <version>]',
      '  Show, approve, or roll back policies.',
      '',
      'Positional:',
      '  show                  List policies (the default with no argument)',
      '  approve <id>          Approve a proposed policy',
      '  rollback <version>    Roll back to a policy version number',
      'Reads: nothing on stdin.',
      'Writes: JSON or a one-line result on stdout; approve and rollback change the local store.',
      'Exit codes: 0 ok, 1 refused (unknown id or version), 2 bad invocation.',
    ),
  },
  evaluate: {
    summary: 'Report the evaluation metrics against their targets',
    body: lines(
      'review-voice evaluate [flags]',
      '  Report the evaluation metrics against their targets.',
      '',
      'Flags:',
      '  --json                 Emit the metrics as JSON',
      'Reads: nothing on stdin; the local store.',
      'Writes: text (or JSON) on stdout.',
      'Exit codes: 0 ok.',
    ),
  },
  draft: {
    summary: 'Render a validated review as a GitHub draft (posts nothing)',
    body: lines(
      'review-voice draft --repository <owner/repo> --pr <number> [flags]',
      '  Render a validated review as a GitHub draft. Posts nothing.',
      '',
      'Flags:',
      '  --repository <name>    owner/repo (required)',
      '  --pr <number>          Pull request number (required)',
      '  --json                 Emit the draft as JSON instead of a preview',
      'Reads: the validated review on stdin.',
      'Writes: the preview (or JSON) on stdout.',
      'Exit codes: 0 ok, 2 bad invocation.',
    ),
  },
  'post-check': {
    summary: 'Report whether posting is permitted, and why not',
    body: lines(
      'review-voice post-check',
      '  Report whether posting is permitted, and why not. Takes no flags.',
      '',
      'Reads: nothing on stdin; the local store and config.',
      'Writes: JSON on stdout.',
      'Exit codes: 0 always (not permitted is an answer, not a failure).',
    ),
  },
  verdict: {
    summary: 'Review event under the head and CI guards (reads only)',
    body: lines(
      'review-voice verdict --pr <number> --head <sha> [flags]',
      '  Compute the review event under the head and CI guards. Reads only.',
      '',
      'Flags:',
      '  --pr <number>          Pull request number (required)',
      '  --head <sha>           Head commit the review read (required)',
      '  --repository <name>    owner/repo; inferred from the git remote if absent',
      '  --run <run-id>         Recorded run to use; default the newest for the pull request',
      '  --recheck              Re-read CI once more before answering',
      'Reads: the validated review on stdin.',
      'Writes: JSON on stdout. Nothing is sent to GitHub.',
      'Exit codes: 0 ok, 2 refused or bad invocation, 3 the head moved, 4 CI still running',
      '  on an approval, 5 a re-check found CI red, 6 CI needs a rerun.',
    ),
  },
  post: {
    summary: 'Submit the review; needs --confirm --event <EVENT>',
    body: lines(
      'review-voice post --pr <number> --head <sha> --confirm --event <EVENT> [flags]',
      '  Submit the review to GitHub. Recomputes the verdict live; sends nothing without --confirm.',
      '',
      'Flags:',
      '  --pr <number>          Pull request number (required)',
      '  --head <sha>           Head commit the review read (required)',
      '  --repository <name>    owner/repo; inferred from the git remote if absent',
      '  --run <run-id>         Recorded run to use; default the newest for the pull request',
      '  --confirm              Send the review; without it, only a preview',
      '  --event <EVENT>        The review event to send (COMMENT, APPROVE or REQUEST_CHANGES)',
      'Reads: the validated review on stdin.',
      'Writes: JSON on stdout. With --confirm, WRITES the review to GitHub (the plugin\'s only write).',
      'Exit codes: 0 sent or previewed, 1 the send failed, 2 refused or bad invocation,',
      '  3 the head moved, 4 CI still running on an approval, 5 CI red, 6 CI needs a rerun.',
    ),
  },
  record: {
    summary: 'Store a validated review from stdin and assign finding ids',
    body: lines(
      'review-voice record [flags]',
      '  Store a validated review and assign finding ids.',
      '',
      'Flags:',
      '  --repository <name>    Repository the review belongs to',
      '  --base <ref>           Base ref reviewed against (on --pr: refs.mergeBase)',
      '  --head <sha>           Head commit reviewed',
      '  --diff-file <path>     Diff the review was produced from (for the run hash)',
      '  --files <path>         files.json from diff --out, carrying pull-request scope',
      '  --candidates <path>    Scored candidates, so findings carry their category',
      '  --scores <path>        Score breakdowns, so explain can show its working',
      '  --verdicts <path>      Verification verdicts, including findings that were dropped',
      '  --tie-breaks <path>    reconcile\'s output, with the rulings it applied',
      '  --held <path>          Candidates held back, as [{"path","line","verdict","source","reason"}]',
      '  --carried-from <run>   Validate findings carried by `carry` (needs --head; run in its clone)',
      '  --carry <path>         carry.json of carry-candidates (needs --head)',
      '  --thread <path>        thread.json; a follow-up whose comment thread is resolved is settled,',
      '                         and with --carried-from, findings `carry --thread` held back stay out',
      '  --follow-ups <path>    The verifier\'s follow_ups rulings on the open follow-ups',
      '  --stages <path>        Per-stage timings as',
      '                         [{"name","seconds","toolCalls","filesRead","tokens"}]; a clean',
      '                         result from a shallow analyst pass is warned about',
      'Reads: the validated review on stdin (a run with no findings pipes',
      `  ${DEFAULT_LIMITS.noFindingsResponse}).`,
      'Writes: the run and its findings to the local store; the run id on stdout.',
      'Exit codes: 0 recorded, 2 not a validated review or bad invocation.',
    ),
  },
  carry: {
    summary: "Carry an earlier run's untouched findings to a new head",
    body: lines(
      'review-voice carry --from <run-id> --head <sha> [--repository <owner/repo>] [--text] [--thread <path>]',
      "  Carry an earlier run's untouched findings to a new head. Commits are read from",
      "  the git repository in the working directory, which must be a clone of the run's",
      '  repository.',
      '',
      'Flags:',
      '  --from <run-id>        The earlier run (required)',
      '  --head <sha>           The new head (required)',
      "  --repository <o/r>     The run's repository, when the run did not record one",
      '  --text                 Print only the carried review, for validate-output',
      '  --thread <path>        thread.json of the same pull request, from `thread`: a finding whose',
      '                         comment thread was resolved, or whose review was dismissed, is held',
      '                         back instead of carried. Without it a pull request run says so.',
      'Reads: nothing on stdin; the local store, and --thread when given.',
      'Writes: JSON (or with --text, the review text) on stdout; what did not carry on stderr.',
      '  JSON adds heldBack: {findingId, path, line, severity, reason}[], not counted as serious findings',
      '  that did not carry; with --text each is on stderr as "Held back: ...".',
      'Exit codes: 0 ok, 1 with --text nothing carried or a serious finding did not, 2 bad invocation.',
    ),
  },
  reanchor: {
    summary: 'Move one scored candidate to a corrected changed line',
    body: lines(
      'review-voice reanchor --candidate <id> --line <n> --scores <path> --diff-file <path> [flags]',
      '  Move one scored candidate to a corrected changed line of --diff-file,',
      '  keeping its score.',
      '',
      'Flags:',
      '  --candidate <id>       Candidate to move (required)',
      '  --line <n>             The changed line to move it to (required)',
      '  --scores <path>        Scores file to rewrite (required)',
      '  --diff-file <path>     Unified diff the line must be changed in (required)',
      '  --path <p>             The file the finding belongs in, if not its current one',
      '  --candidates <path>    Candidates file to rewrite alongside --scores',
      'Reads: nothing on stdin.',
      'Writes: rewrites --scores (and --candidates when given); a summary on stdout.',
      'Exit codes: 0 moved, 1 refused (the line is not a changed line), 2 bad invocation or unreadable input.',
    ),
  },
  'carry-candidates': {
    summary: 'Carry verified candidates to a pushed head if unchanged',
    body: lines(
      'review-voice carry-candidates --candidates <path> --verification <path> --since <sha>',
      '    --head <sha> --diff-file <path> --out <dir> [flags]',
      '  Carry verified candidates to a pushed head if unchanged.',
      '',
      'Flags:',
      '  --candidates <path>    Candidates of the earlier run (required)',
      '  --verification <path>  Verifier output of the earlier run (required)',
      '  --since <sha>          The head the earlier run reviewed (required)',
      '  --head <sha>           The new head (required)',
      "  --diff-file <path>     The whole pull request's diff at the new head, from",
      '                         `diff --pr <number> --full` (required); an interdiff is refused',
      '  --out <dir>            Directory to write the carried files into (required)',
      '  --interdiff <dir>      The reviewed commits between the heads, merged in',
      '  --interdiff-candidates <path>     Candidates of those commits (with --interdiff)',
      '  --interdiff-verification <path>   Verification of those commits (with --interdiff)',
      '  --held <path>          Held findings to move to the new head',
      'Reads: nothing on stdin.',
      'Writes: carried candidates, verification and carry.json under --out; a summary on stdout.',
      'Exit codes: 0 every candidate carried, 1 at least one was refused, 2 bad invocation,',
      '  unreadable input or an interdiff --diff-file.',
    ),
  },
  feedback: {
    summary: 'Record feedback on a finding',
    body: lines(
      'review-voice feedback <rv_NN|run-id:rv_NN> <action> [flags]',
      '  Record feedback on a finding.',
      '',
      'Positional:',
      '  <rv_NN|run-id:rv_NN>   The finding (required)',
      `  <action>               ${FEEDBACK_ACTIONS.join(', ')} (hyphens accepted)`,
      'Flags:',
      '  --reason <text>        Why',
      '  --replacement <text>   The wording to prefer (for a rewrite)',
      'Reads: nothing on stdin.',
      'Writes: one feedback record to the local store.',
      'Exit codes: 0 recorded, 1 unknown finding, 2 bad invocation or action.',
    ),
  },
  status: {
    summary: 'Show what is stored locally',
    body: lines(
      'review-voice status',
      '  Show what is stored locally. Takes no flags.',
      '',
      'Reads: nothing on stdin; the local store and config.',
      'Writes: text on stdout.',
      'Exit codes: 0 ok.',
    ),
  },
  explain: {
    summary: 'Show why the last review said what it said',
    body: lines(
      'review-voice explain [flags]',
      '  Show why a recorded review emitted or suppressed each finding.',
      '',
      'Flags:',
      '  --run <run-id>         The run to explain; default the latest',
      '  --json                 Emit the detail as JSON',
      'Reads: nothing on stdin; the local store.',
      'Writes: text (or JSON) on stdout.',
      'Exit codes: 0 ok.',
    ),
  },
  'validate-output': {
    summary: 'Enforce the output contract on a review read from stdin',
    body: lines(
      'review-voice validate-output [flags]',
      '  Enforce the output contract on a review.',
      '',
      'Flags:',
      '  --json                     Emit the result as JSON',
      '  --max-findings <n>         Default: no cap',
      '  --scale-to-files <n>       Scale the total word budget to the change size',
      `  --max-words-per-finding <n>  Default ${DEFAULT_LIMITS.maxWordsPerFinding}`,
      `  --max-total-words <n>      Default ${DEFAULT_LIMITS.maxTotalWords}`,
      '  --scores <path>            The JSON `score` printed; a severity tag that disagrees with its score,',
      '                             or an absolute word (every, always, never, all) the scored finding',
      '                             does not use, is a violation',
      'Reads: the review text on stdin.',
      'Writes: the result on stdout.',
      'Exit codes: 0 compliant, 1 violations found, 2 bad invocation.',
    ),
  },
  doctor: {
    summary: 'Check that this machine can run Review Voice',
    body: lines(
      'review-voice doctor',
      '  Check that this machine can run Review Voice. Takes no flags.',
      '',
      'Reads: nothing on stdin.',
      'Writes: one line per check on stdout.',
      'Exit codes: 0 every required check passed (gh is optional), 1 a required check failed.',
    ),
  },
};

/** The order commands are listed in; every dispatched command appears once. */
export const COMMAND_ORDER = Object.keys(COMMAND_HELP);

/** One command's help section, or null when there is no such command. */
export function commandHelp(command: string): string | null {
  return Object.hasOwn(COMMAND_HELP, command) ? COMMAND_HELP[command]!.body : null;
}

export function topLevelHelp(): string {
  const list = COMMAND_ORDER.map((name) => `  ${name.padEnd(20)}${COMMAND_HELP[name]!.summary}`);
  const reference = COMMAND_ORDER.map((name) => COMMAND_HELP[name]!.body);
  return [
    'review-voice <command>',
    '',
    'Commands:',
    ...list,
    '  --version           Print the plugin version',
    '  --help              Show this message',
    '',
    'Run `review-voice <command> --help` for one command\'s flags.',
    '',
    reference.join('\n\n'),
    '',
    'Exit codes: 0 compliant, 1 violations found, 2 bad invocation.',
    '',
    'Normally driven by the /review-voice:* commands, not invoked directly.',
  ].join('\n');
}
